### PR TITLE
Changed the dbms.md file and modified the roles.md file which I had it messed up in my local repository.

### LINKED ISSUE #74: Review the contents of the file dbms.md

### PR DESCRIPTION
**Pull request by JaimeRuiz06**
close #74

### CODE REVIEW

**Review by tamasi17 — APPROVED** [review]
well done James gg

**Review by JaimeRuiz06 — COMMENTED** [review]
Aprobadme la pull request porfa.
stock-vector-homeless-beggar-emoticon-begging-for-money-1330219121

**Review by daniela898 — CHANGES_REQUESTED** [review]
Revisa la guia de formato, para los títulos usamos dos # y tienes tres * que no deberían estar ahi, en las lineas 1, 18, 22

**Review by DGuelar — APPROVED** [review]

**Review by DGuelar — APPROVED** [review]

**Review by AlexWhut — APPROVED** [review]

**Review by daniela898 — APPROVED** [review]

**Review by Lowri-ui — CHANGES_REQUESTED** [review]
Please review the content, there is missing information about the original dbms.md file. Thank you!

**Review by Lowri-ui — APPROVED** [review]
Perfect! All the information has been added.

**Pull request merged**
