### PR TITLE
Add other

### LINKED ISSUE #52: Create the other.md file
Create a folder named `unit1`, and a file `other.md`
In the `other`.md file, explain the following concepts:

- DML
- DDL
- DCL
- TCL

Codd's 12 rules

SQL injection

### PR DESCRIPTION
**Pull request by symn369**
closes #52

### CODE REVIEW

**Review by Sosoloogic — APPROVED** [review]
i did a check everything is good 👍

**Review by tamasi17 — APPROVED** [review]
all correct, good job

**Comment by tamasi17** [comment]
@bananas24 can you be the third reviewer please?

**Review by ErGeorgi — APPROVED** [review]
I love it! It's very well explained. Doesn't look human! 🤯
All of the definitions are easy to understand and comprehend 🙂
Keep up like that 😁

**Comment by tamasi17** [comment]
> WIP

@Sosoloogic and I rebased and pushed our last version, please check to see if it is ready for merging.

**Review by YuUs01 — APPROVED** [review]

**Review by bananas24 — APPROVED** [review]

**Pull request merged**
