### PR TITLE
Changed the style to be like the guide and added visual support

### LINKED ISSUE #76: Review the contents of the roles.md file
The team (or representative by default) has to review the content of the file assigned, as well as the format.

### PR DESCRIPTION
**Pull request by YuUs01**
closes #76

### CODE REVIEW

**Review by DGuelar — CHANGES_REQUESTED** [review]
Add the # and close the three ```

**Review by YuUs01 — COMMENTED** [review]
all the changes requested by @DGuelar have been met

**Review by AlexWhut — APPROVED** [review]
Review the changes, and confirm if they are correct.

**Review by DGuelar — APPROVED** [review]

**Review by JaimeRuiz06 — APPROVED** [review]
image

**Pull request merged**
