### PR TITLE
adding dbms file to main

### LINKED ISSUE #49: create the dbms.md
Create a folder named `unit1`, and a file `dmbs.md`
In the `dbms.md` file, explain the following concepts:

DBMS examples
Oracle
MySQL
DB2

other:
BI
ETL

Languages:
PL-SQL
php, c++

### PR DESCRIPTION
**Pull request by Montezz14**
Angel, Laura, Marcos and Jorge Montero.
Unit 1 dbms file.
close #49

### CODE REVIEW

**Review by bananas24 — CHANGES_REQUESTED** [review]
WIP

**Review by Karls3fni — APPROVED** [review]

**Review by ItsKein — APPROVED** [review]

**Comment by Karls3fni** [comment]
Good one

**Review by Marcos-18-11 — APPROVED** [review]
Very good

**Review by Sosoloogic — APPROVED** [review]
nice work guys

**Comment by tamasi17** [comment]
Content looks fine!
I suggest formatting with titles and bolds for better readability 🤍

**Review by ItsKein — APPROVED** [review]

**Review by AlexWhut — APPROVED** [review]

**Review by AlexWhut — APPROVED** [review]

**Review by AlexWhut — APPROVED** [review]

**Comment by Lowri-ui** [comment]
Good afternoon, @bananas24. We have updated the changes you requested, and the file has been completed and reviewed.
Could you please undo the change request so we can close de PR? Thank you!
By the way, i've done the git rebase for the branch "bdms_file", I hope it's ok. 

image

**Pull request merged**
